/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import com.mysql.jdbc.PreparedStatement;
import controllers.PontParametres;
import controllers.UsersBD;
import controllers.Ventes;
import javax.swing.JOptionPane;
import java.io.*;
import java.text.DateFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import modeles.easy_sales;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author InfoSys Tech
 */
public class adminConnexion extends javax.swing.JFrame {

    /**
     * Creates new form Cnxion
     */
    public adminConnexion() {
        initComponents();
        initBiloko();
        this.setTitle("Connexion Foreign Base Dynamique ...");
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        try{
            this.setIconImage(new ImageIcon(getClass().getResource("/LesImages/HPP_Congo.jpg")).getImage());//donne l'icon au formulaire
        }catch  (Exception ex){
            JOptionPane.showMessageDialog(this, "Erreur : "+ex.getMessage(), "Easy Sales", JOptionPane.OK_OPTION);
            return;
        }
    }

    void initBiloko(){
        btnHJ.setSelected(true);
        btnSolde.setSelected(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        zUserN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        zpwd = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnHJ = new javax.swing.JRadioButton();
        btnSolde = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel1.setText("User Name :");

        zUserN.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel2.setText("Pass Word :");

        zpwd.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jButton2.setText("Quitter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnHJ.setText("Heure de Joie");
        btnHJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHJActionPerformed(evt);
            }
        });

        btnSolde.setText("Solde");
        btnSolde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoldeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(zUserN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(zpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSolde)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHJ)
                    .addComponent(btnSolde))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(zUserN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(zpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(37, 37, 37))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LesImages/HPP_Congo.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed
    Ventes vt=null;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String us=this.zUserN.getText(), pd=Arrays.toString(zpwd.getPassword());
            vt = new Ventes();
            UsersBD user = new UsersBD();
            boolean users = user.trouverAdmin(us, pd);
            if(users){
                if (btnHJ.isSelected()) {
                    boolean hj = vt.heureDeJoie();
                    if (!hj) {
                        vt.creerParam("HEURE DE JOIE");
                        JOptionPane.showMessageDialog(this, "Heure de Joie Créer", "Easy Sales", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        int msg = JOptionPane.showConfirmDialog(this, "Mettre fin à l'Heure de Joie ?", "Easy Sales", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (msg == JOptionPane.YES_OPTION) {
                        vt.fermerListeHJ();
                        /**
                         * Impression donnée Heure de Joie
                         */
                        impressionHJ();
                        /**
                         * Fin Impression donnée Heure de Joie
                         */
                            vt.tuerParam("HEURE DE JOIE");
                        }
                    }
                }else if(btnSolde.isSelected()){
                    String z = vt.paramVentes();
                    if (z.equals("SOLDE")) {
                        vt.tuerParam("SOLDE");
                        vt.creerParam("NORMAL");
                        JOptionPane.showMessageDialog(this, "Nouvelle Semaine Créée", "Easy Sales", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        vt.tuerParam("HEURE DE JOIE");
                        vt.tuerParam("NORMAL");
                        vt.creerParam("SOLDE");
                        JOptionPane.showMessageDialog(this, "Type de Vente : Solde", "Easy Sales", JOptionPane.INFORMATION_MESSAGE);
                    }                    
                }
                
                dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Vous devez être minimum Gérant(e) pour modifier un état", "Easy Sales", JOptionPane.WARNING_MESSAGE);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Erreur : "+e.getMessage(), "Magnific Base Dynamique", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    void impressionHJ(){
        
        int numD = vt.numeroDHJetJ100("heuredejoie", "numeroD");
        int numF = vt.numeroDHJetJ100("heuredejoie", "numeroF");
        try {
            easy_sales.connexionEasy();
            easy_sales.Pst = (PreparedStatement) easy_sales.cn.clientPrepareStatement("SELECT idArticles, sum(QTEVENTE), sum(QTEVENTE * prixVente) FROM Ventes WHERE idSite = ? AND idVentes BETWEEN ? AND ? "
                    + " GROUP BY idArticles");
            easy_sales.Pst.setString(1, PontParametres.site);
            easy_sales.Pst.setInt(2, numD);
            easy_sales.Pst.setInt(3, numF);
            easy_sales.rs = easy_sales.Pst.executeQuery();
            if (easy_sales.rs.next()) {
                Map para = new HashMap();
                para.put("numeroD", numD);
                para.put("numeroF", numF);
                para.put("site", PontParametres.site);
                JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("etats/heureDJ.jasper"),para,easy_sales.cn);
                JasperViewer.viewReport(jp, false);
            }
        } catch (Exception e) {
            System.err.println("Erreur : "+e.getMessage());
        }
    }
    DateFormatSymbols dtf=new DateFormatSymbols();
    SimpleDateFormat sdt=new SimpleDateFormat("yyyy-MM-dd",dtf);
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnHJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHJActionPerformed
        // TODO add your handling code here:
        btnSolde.setSelected(false);
    }//GEN-LAST:event_btnHJActionPerformed

    private void btnSoldeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoldeActionPerformed
        // TODO add your handling code here:
        btnHJ.setSelected(false);
    }//GEN-LAST:event_btnSoldeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminConnexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnHJ;
    private javax.swing.JRadioButton btnSolde;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField zUserN;
    private javax.swing.JPasswordField zpwd;
    // End of variables declaration//GEN-END:variables
}
