/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import com.mysql.cj.jdbc.ClientPreparedStatement;
import controllers.TravailUsers;
import controllers.UsersBD;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modeles.easy_sales;

/**
 *
 * @author user
 */
public class usersInterface extends javax.swing.JInternalFrame {

    /**
     * Creates new form usersInterface
     */
    public usersInterface() {
        initComponents();
        setLocation(100, 150);
        nettoie();
    }

    void nettoie(){
        txtUserID.setText(null);
        txtNomComplet.setText(null);
        txtPwd.setEditable(false);
        BTNuser.setSelected(true);
        chargerTableUser();
        cbStatus.setSelectedIndex(0);
        txtSiteID.setText(null);
        txtSiteID.setEditable(false);
        txtUserID.requestFocus();
    }
    boolean verifieZone(){
        boolean vr = false;
        try {
            if (!txtSiteID.getText().equalsIgnoreCase(null) && !txtUserID.getText().equalsIgnoreCase(null) && cbStatus.getSelectedIndex()!= 0) {
                vr = true;
            }
        } catch (Exception e) {
            System.err.println("Erreur : "+e.getMessage());
        }
        return vr;
    }
    UsersBD user = null;
    void appelUser(){
        user = new UsersBD(txtUserID.getText().toUpperCase().trim(), txtNomComplet.getText().toUpperCase().trim(), cbStatus.getSelectedItem().toString().trim(), txtPwd.getText().trim());
    }
    TravailUsers TU = null;
    void appelTravail(){
        TU = new TravailUsers(txtUserID.getText().trim().toUpperCase(), txtSiteID.getText().toUpperCase().trim());
    }
    DefaultTableModel dt;
    void chargerTableUser(){
        try {
            dt = new DefaultTableModel();
            dt.addColumn("ID");
            dt.addColumn("Nom Complet");
            dt.addColumn("Status");
            dt.addColumn("PWD");
            tblMix.setModel(dt);
            tblMix.getColumn("ID").setMaxWidth(100);
            tblMix.getColumn("Status").setMaxWidth(200);
            tblMix.getColumn("PWD").setMaxWidth(0);
            easy_sales.connexionEasy();
            easy_sales.Pst = (ClientPreparedStatement) easy_sales.cn.prepareStatement("SELECT idUsers, nomcomplet, statuts, pwd FROM UsersBD");
            easy_sales.rs = easy_sales.Pst.executeQuery();
            while (easy_sales.rs.next()) {                
                Object a,b,c,d;
                a = easy_sales.rs.getObject(1);
                b = easy_sales.rs.getObject(2);
                c = easy_sales.rs.getObject(3);
                d = easy_sales.rs.getObject(4);
                Object [] e = {a,b,c,d};
                dt.addRow(e);
            }
            tblMix.setModel(dt);
            easy_sales.deconnexionEasy();
        } catch (Exception e) {
            System.err.println("Erreur : "+e.getMessage());
        }
    }
    void chargerTablSite(){
        try {
            dt = new DefaultTableModel();
            dt.addColumn("ID");
            dt.addColumn("Nom Site");
            dt.addColumn("Adresse");
            tblMix.setModel(dt);
            tblMix.getColumn("ID").setMaxWidth(100);
            tblMix.getColumn("Nom Site").setMaxWidth(200);
            tblMix.getColumn("Adresse").setMinWidth(100);
            easy_sales.connexionEasy();
            easy_sales.Pst = (ClientPreparedStatement)  easy_sales.cn.prepareStatement("SELECT idSite, libSite, adresse FROM sites");
            easy_sales.rs = easy_sales.Pst.executeQuery();
            while (easy_sales.rs.next()) {                
                Object a,b,c;
                a = easy_sales.rs.getObject(1);
                b = easy_sales.rs.getObject(2);
                c = easy_sales.rs.getObject(3);
                Object [] e = {a,b,c};
                dt.addRow(e);
            }
            tblMix.setModel(dt);
            easy_sales.deconnexionEasy();
        } catch (Exception e) {
            System.err.println("Erreur : "+e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BTNsite = new javax.swing.JRadioButton();
        BTNuser = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMix = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtUserID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSiteID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomComplet = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPwd = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        BTNsite.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        BTNsite.setText("Les Sites de Travail");
        BTNsite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsiteActionPerformed(evt);
            }
        });

        BTNuser.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        BTNuser.setText("Les Users");
        BTNuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNuserActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Les Informations :"));

        tblMix.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMixMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMix);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ajouter un site");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        txtUserID.setText("jTextField1");

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel1.setText("Code Utilisateur :");

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel3.setText("Site de Travail :");

        txtSiteID.setText("jTextField1");

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel2.setText("Nom Complet :");

        txtNomComplet.setText("jTextField1");

        cbStatus.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------------", "Administrateur", "Caissier", "Gérant" }));

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel4.setText("Status :");

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel5.setText("Mot Passe par Defaut :");

        txtPwd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPwd.setText("123");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(txtSiteID, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomComplet)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPwd, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomComplet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSiteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(BTNsite)
                        .addGap(141, 141, 141)
                        .addComponent(BTNuser)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNsite)
                    .addComponent(BTNuser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            int msg = JOptionPane.showConfirmDialog(this, "Les données sont - elles correctes ?", "Easy Sales", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (msg == JOptionPane.YES_OPTION) {
                boolean vr = verifieZone();
                if (vr) {
                    appelUser(); appelTravail();
                    boolean tr = user.rechercherUser();
                    if (tr) {
                        int msg1 = JOptionPane.showConfirmDialog(this, "Cet'Utilisateur existe déjà, voulez vous le modifier ?", "Easy Sales", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (msg1== JOptionPane.YES_OPTION) {
                            user.modifier();
                            TU.finTravail();
                            TU.enregistrerTravail();
                            JOptionPane.showMessageDialog(this, "Modifications effectuée", "Easy Sales", JOptionPane.INFORMATION_MESSAGE);
                            nettoie();
                        }
                    }else{
                        user.enregistrer();
                        TU.finTravail();
                        TU.enregistrerTravail();
                        JOptionPane.showMessageDialog(this, "Enregistrement effectué", "Easy Sales", JOptionPane.INFORMATION_MESSAGE);
                        nettoie();
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Remplissez toutes les zones Obligatoires SVP", "Easy Sales", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur : "+e.getMessage(), "Easy Sales", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BTNsiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsiteActionPerformed
        // TODO add your handling code here:
        if (BTNuser.isSelected()) {
            BTNuser.setSelected(false);
            BTNsite.setSelected(true);
            chargerTablSite();
        }
    }//GEN-LAST:event_BTNsiteActionPerformed

    private void BTNuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNuserActionPerformed
        // TODO add your handling code here:
        if (BTNsite.isSelected()) {
            BTNsite.setSelected(false);
            BTNuser.setSelected(true);
            chargerTableUser();
        }
    }//GEN-LAST:event_BTNuserActionPerformed

    private void tblMixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMixMouseClicked
        // TODO add your handling code here:
        if (BTNuser.isSelected()) {
            txtUserID.setText(tblMix.getValueAt(tblMix.getSelectedRow(), 0).toString());
            txtNomComplet.setText(tblMix.getValueAt(tblMix.getSelectedRow(), 1).toString());
            txtPwd.setText(tblMix.getValueAt(tblMix.getSelectedRow(), 3).toString());
            cbStatus.setSelectedItem(tblMix.getValueAt(tblMix.getSelectedRow(), 2).toString());
        }else{
            txtSiteID.setText(tblMix.getValueAt(tblMix.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_tblMixMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BTNsite;
    private javax.swing.JRadioButton BTNuser;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMix;
    private javax.swing.JTextField txtNomComplet;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JTextField txtSiteID;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
}
